# 强制使用硬件解码
hwdec=auto-safe
#hwdec=vaapi
hwdec-codecs=all

vo=gpu-next
gpu-api=vulkan
#profile=fast
profile=high-quality


scale=bilinear
cscale=bilinear
dscale=bilinear
deband=no

video-sync=display-resample

