# 强制开启原生 Wayland 支持（摆脱 Xwayland 的模糊和性能损耗）
--ozone-platform-hint=auto
--enable-features=WaylandWindowDecorations

# 启用 GPU 硬件加速
--ignore-gpu-blocklist
--enable-gpu-rasterization
--enable-zero-copy

# 开启硬件视频解码（看 B站/YouTube 极度降温，配合下方的 VA-API 选项）
--enable-features=VaapiVideoDecodeLinuxGL

# 启用 Vulkan 后端（可选，对某些 AMD/Intel 显卡能进一步提升流畅度，N卡慎用）
# --enable-features=Vulkan

# --use-gl=angle
# --use-angle=gl
# --disable-gpu-sandbox
# --enable-features=Vulkan


# # 开启平滑滚动（让鼠标滚轮和触控板滑动更丝滑）
--enable-smooth-scrolling

# 强制启用深色模式（如果你的系统主题是深色的，让网页也默认适配）
# --enable-features=WebUIDarkMode
# --force-dark-mode

# 启用并联下载（类似 IDM，多线程下载大文件速度更快）
# --enable-features=ParallelDownloading

# 优化内存占用（自动冻结后台闲置标签页）
# --enable-features=HighEfficiencyModeFeatures
